### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by aka004db** [GreyCorbel/SIDCloner#1]
I've compiled the solution using Visual Studio. Now a DLL-file is created. I've put it in to the System32-folder on a Domain controller. When I try to do the reflection with PowerShell, I get this result:

PS C:\Windows\system32> [System.Reflection.Assembly]::LoadFile("C:\Windows\System32\SIDCloner.dll")
Exception calling "LoadFile" with "1" argument(s): "Could not load file or assembly 'SIDCloner.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)"
At line:1 char:1
+ [System.Reflection.Assembly]::LoadFile("C:\Windows\System32\SIDCloner ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : BadImageFormatException
 

Am I missing dependencies, is something wrong with the settings of Visual Studio?
What am i missing?

Cheers

**Comment by jformacek** [comment]
This is most likely because your machine does not have VC++ redistributable installed. There used to be a way to compile with /MT instead of /MD switch, but this is no longer supported and CRL support is not compatible with static linking to C++ runtime.  
See [here](https://stackoverflow.com/questions/938539/why-is-clr-incompatible-with-mt-and-mtd-in-visual-studio) for details.  
So your only option is currently to make sure that you have VC++ runtime installed on target machine.  
I can confirm That on my test machine with VC++ runtime, I'm able to load the assembly without any problems:
```powershell
PS C:\Users\JiriFormacek> [system.reflection.assembly]::LoadFile("C:\TFS\github.com\SIDCloner\x64\Release\SIDCloner.dll")

GAC    Version        Location
---    -------        --------
False  v4.0.30319     C:\TFS\github.com\SIDCloner\x64\Release\SIDCloner.dll

```

Hope this helps,
Jiri

**Comment by aka004db** [comment]
Hé Jiri,

Thanks for your reply and your efforts!

Unfortunately it still doesn't work on my machine.
I don't get it... Installed the "Microsoft Visual C++ 2008" and "Microsoft Visual C++ 2015-2019" for x64 and x86
Still the same error. Could it be I use the wrong settings while compiling? I can't even get the reflection working on the same machine the code is compiled? That seems weird, doesn't it? The solution builds successfully without errors or warnings.

Is it possible you transfer the dll to me somehow just to make sure it isn't a compiling mistake?

Thanks in advance
Arjan

**Comment by aka004db** [comment]
[SIDCloner.zip](https://github.com/GreyCorbel/SIDCloner/files/5674361/SIDCloner.zip)
This is mine ;-)

**Comment by jformacek** [comment]
See my answer via mail, there are compiled binaries attached. I would say that you were trying to import x86 binaries into x64 process

Jiri

**Comment by aka004db** [comment]
Thanks a million! This is working. I will try to find out my own building parameters, but you helped me out of a tough spot right now. I'm very grateful!

Cheers

Arjan

**Comment by jformacek** [comment]
Thank you. Let’s close the issue now. 
Jiri

**Comment by aka004db** [comment]
Jiri helped me out
Issue is resolved ;-)

**Comment by Haramyde** [comment]
Hi @jformacek  Looks like I've got the same problem as @aka004db 
With my checks, I want to believe I have the pre-requisite on my box, but still unable to install the module

PS C:\Program Files\WindowsPowerShell\Modules\sidcloner> [system.reflection.assembly]::LoadFile("C:\Program Files\WindowsPowerShell\Modules\sidcloner\SIDCloner.dll")

GAC      Version           Location

False     v4.0.30319        C:\Program Files\WindowsPowerShell\Modules\sidcloner\SIDCloner.dll

Would you have any suggestion on how to TS this?  Thanks!

**Comment by mathewhunter** [comment]
Just my 2 cents a long time after this was closed:
you can't install this on a member server, has to be a DC.  you can use dependency crawler on a member server to see how lots of dependencies are missing.
